application: snapnote-app
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /script.js
  mime_type: text/javascript
  static_files: script.js
  upload: script\.js

- url: /postTest
  script: postTest.php

- url: /processText.php
  script: processText.php

- url: /getPng
  script: getPng.php

- url: /test
  mime_type: image/tiff
  static_files: sample.tiff
  upload: sample\.tiff

- url: .*
  script: main.php
